// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/3110Y/cap/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMarketplaceLister is a mock of the marketplaceLister interface.
type MockMarketplaceLister struct {
	ctrl     *gomock.Controller
	recorder *MockMarketplaceListerMockRecorder
	isgomock struct{}
}

// MockMarketplaceListerMockRecorder is the mock recorder for MockMarketplaceLister.
type MockMarketplaceListerMockRecorder struct {
	mock *MockMarketplaceLister
}

// NewMockMarketplaceLister creates a new mock instance.
func NewMockMarketplaceLister(ctrl *gomock.Controller) *MockMarketplaceLister {
	mock := &MockMarketplaceLister{ctrl: ctrl}
	mock.recorder = &MockMarketplaceListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketplaceLister) EXPECT() *MockMarketplaceListerMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockMarketplaceLister) Info(primitiveType, name, version string) ([]*entity.Primitive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", primitiveType, name, version)
	ret0, _ := ret[0].([]*entity.Primitive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockMarketplaceListerMockRecorder) Info(primitiveType, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockMarketplaceLister)(nil).Info), primitiveType, name, version)
}

// List mocks base method.
func (m *MockMarketplaceLister) List(primitiveType string) ([]*entity.Primitive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", primitiveType)
	ret0, _ := ret[0].([]*entity.Primitive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMarketplaceListerMockRecorder) List(primitiveType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMarketplaceLister)(nil).List), primitiveType)
}
