// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/cache_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/cache_repository.go -destination=internal/integration/mocks/mock_cache_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/3110Y/cap/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// ListCachedIDs mocks base method.
func (m *MockCacheRepository) ListCachedIDs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCachedIDs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCachedIDs indicates an expected call of ListCachedIDs.
func (mr *MockCacheRepositoryMockRecorder) ListCachedIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCachedIDs", reflect.TypeOf((*MockCacheRepository)(nil).ListCachedIDs))
}

// ReadIndex mocks base method.
func (m *MockCacheRepository) ReadIndex(id string) ([]*entity.Primitive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadIndex", id)
	ret0, _ := ret[0].([]*entity.Primitive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadIndex indicates an expected call of ReadIndex.
func (mr *MockCacheRepositoryMockRecorder) ReadIndex(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadIndex", reflect.TypeOf((*MockCacheRepository)(nil).ReadIndex), id)
}

// ReadIndexes mocks base method.
func (m *MockCacheRepository) ReadIndexes() ([]*entity.Primitive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadIndexes")
	ret0, _ := ret[0].([]*entity.Primitive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadIndexes indicates an expected call of ReadIndexes.
func (mr *MockCacheRepositoryMockRecorder) ReadIndexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadIndexes", reflect.TypeOf((*MockCacheRepository)(nil).ReadIndexes))
}

// RemoveRepo mocks base method.
func (m *MockCacheRepository) RemoveRepo(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRepo", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRepo indicates an expected call of RemoveRepo.
func (mr *MockCacheRepositoryMockRecorder) RemoveRepo(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRepo", reflect.TypeOf((*MockCacheRepository)(nil).RemoveRepo), id)
}

// RepoDir mocks base method.
func (m *MockCacheRepository) RepoDir(id string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoDir", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// RepoDir indicates an expected call of RepoDir.
func (mr *MockCacheRepositoryMockRecorder) RepoDir(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoDir", reflect.TypeOf((*MockCacheRepository)(nil).RepoDir), id)
}

// WriteIndexes mocks base method.
func (m *MockCacheRepository) WriteIndexes(primitives []*entity.Primitive) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteIndexes", primitives)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteIndexes indicates an expected call of WriteIndexes.
func (mr *MockCacheRepositoryMockRecorder) WriteIndexes(primitives any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteIndexes", reflect.TypeOf((*MockCacheRepository)(nil).WriteIndexes), primitives)
}
