// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/self_update_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/self_update_repository.go -destination=internal/integration/mocks/mock_self_update_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSelfUpdateRepository is a mock of SelfUpdateRepository interface.
type MockSelfUpdateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSelfUpdateRepositoryMockRecorder
	isgomock struct{}
}

// MockSelfUpdateRepositoryMockRecorder is the mock recorder for MockSelfUpdateRepository.
type MockSelfUpdateRepositoryMockRecorder struct {
	mock *MockSelfUpdateRepository
}

// NewMockSelfUpdateRepository creates a new mock instance.
func NewMockSelfUpdateRepository(ctrl *gomock.Controller) *MockSelfUpdateRepository {
	mock := &MockSelfUpdateRepository{ctrl: ctrl}
	mock.recorder = &MockSelfUpdateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSelfUpdateRepository) EXPECT() *MockSelfUpdateRepositoryMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockSelfUpdateRepository) Download(version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockSelfUpdateRepositoryMockRecorder) Download(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockSelfUpdateRepository)(nil).Download), version)
}

// LatestVersion mocks base method.
func (m *MockSelfUpdateRepository) LatestVersion() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersion")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestVersion indicates an expected call of LatestVersion.
func (mr *MockSelfUpdateRepositoryMockRecorder) LatestVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersion", reflect.TypeOf((*MockSelfUpdateRepository)(nil).LatestVersion))
}
