// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/git_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/git_client.go -destination=internal/integration/mocks/mock_git_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitClient is a mock of GitClient interface.
type MockGitClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitClientMockRecorder
	isgomock struct{}
}

// MockGitClientMockRecorder is the mock recorder for MockGitClient.
type MockGitClientMockRecorder struct {
	mock *MockGitClient
}

// NewMockGitClient creates a new mock instance.
func NewMockGitClient(ctrl *gomock.Controller) *MockGitClient {
	mock := &MockGitClient{ctrl: ctrl}
	mock.recorder = &MockGitClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitClient) EXPECT() *MockGitClientMockRecorder {
	return m.recorder
}

// CloneOrFetch mocks base method.
func (m *MockGitClient) CloneOrFetch(url, dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneOrFetch", url, dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloneOrFetch indicates an expected call of CloneOrFetch.
func (mr *MockGitClientMockRecorder) CloneOrFetch(url, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneOrFetch", reflect.TypeOf((*MockGitClient)(nil).CloneOrFetch), url, dir)
}
