// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/project_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/project_repository.go -destination=internal/integration/mocks/mock_project_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// FindDotClaude mocks base method.
func (m *MockProjectRepository) FindDotClaude() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDotClaude")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDotClaude indicates an expected call of FindDotClaude.
func (mr *MockProjectRepositoryMockRecorder) FindDotClaude() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDotClaude", reflect.TypeOf((*MockProjectRepository)(nil).FindDotClaude))
}

// Install mocks base method.
func (m *MockProjectRepository) Install(sourceDir, primitiveType, vendor, name, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", sourceDir, primitiveType, vendor, name, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockProjectRepositoryMockRecorder) Install(sourceDir, primitiveType, vendor, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockProjectRepository)(nil).Install), sourceDir, primitiveType, vendor, name, version)
}
