// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/repository_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/repository_repository.go -destination=internal/integration/mocks/mock_repository_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/3110Y/cap/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryRepository is a mock of RepositoryRepository interface.
type MockRepositoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryRepositoryMockRecorder is the mock recorder for MockRepositoryRepository.
type MockRepositoryRepositoryMockRecorder struct {
	mock *MockRepositoryRepository
}

// NewMockRepositoryRepository creates a new mock instance.
func NewMockRepositoryRepository(ctrl *gomock.Controller) *MockRepositoryRepository {
	mock := &MockRepositoryRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryRepository) EXPECT() *MockRepositoryRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRepositoryRepository) Add(repo *entity.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRepositoryRepositoryMockRecorder) Add(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepositoryRepository)(nil).Add), repo)
}

// Delete mocks base method.
func (m *MockRepositoryRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepositoryRepository)(nil).Delete), id)
}

// List mocks base method.
func (m *MockRepositoryRepository) List() ([]*entity.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*entity.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryRepository)(nil).List))
}
