// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/installed_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/installed_repository.go -destination=internal/integration/mocks/mock_installed_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/3110Y/cap/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockInstalledRepository is a mock of InstalledRepository interface.
type MockInstalledRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInstalledRepositoryMockRecorder
	isgomock struct{}
}

// MockInstalledRepositoryMockRecorder is the mock recorder for MockInstalledRepository.
type MockInstalledRepositoryMockRecorder struct {
	mock *MockInstalledRepository
}

// NewMockInstalledRepository creates a new mock instance.
func NewMockInstalledRepository(ctrl *gomock.Controller) *MockInstalledRepository {
	mock := &MockInstalledRepository{ctrl: ctrl}
	mock.recorder = &MockInstalledRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstalledRepository) EXPECT() *MockInstalledRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockInstalledRepository) Delete(primitiveType, vendor, name, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", primitiveType, vendor, name, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstalledRepositoryMockRecorder) Delete(primitiveType, vendor, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstalledRepository)(nil).Delete), primitiveType, vendor, name, version)
}

// List mocks base method.
func (m *MockInstalledRepository) List(primitiveType string) ([]*entity.Primitive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", primitiveType)
	ret0, _ := ret[0].([]*entity.Primitive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInstalledRepositoryMockRecorder) List(primitiveType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInstalledRepository)(nil).List), primitiveType)
}
