// Code generated by MockGen. DO NOT EDIT.

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/3110Y/cap/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPrimitiveInstaller is a mock of the primitiveInstaller interface.
type MockPrimitiveInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockPrimitiveInstallerMockRecorder
	isgomock struct{}
}

// MockPrimitiveInstallerMockRecorder is the mock recorder for MockPrimitiveInstaller.
type MockPrimitiveInstallerMockRecorder struct {
	mock *MockPrimitiveInstaller
}

// NewMockPrimitiveInstaller creates a new mock instance.
func NewMockPrimitiveInstaller(ctrl *gomock.Controller) *MockPrimitiveInstaller {
	mock := &MockPrimitiveInstaller{ctrl: ctrl}
	mock.recorder = &MockPrimitiveInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrimitiveInstaller) EXPECT() *MockPrimitiveInstallerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPrimitiveInstaller) Add(primitiveType, name, version string) (*entity.Primitive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", primitiveType, name, version)
	ret0, _ := ret[0].(*entity.Primitive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockPrimitiveInstallerMockRecorder) Add(primitiveType, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPrimitiveInstaller)(nil).Add), primitiveType, name, version)
}
