// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/3110Y/cap/internal/application/service"
	"github.com/3110Y/cap/internal/integration/external"
	"github.com/3110Y/cap/internal/integration/repository"
	"github.com/3110Y/cap/internal/presentation/command"
	"github.com/3110Y/cap/internal/presentation/handler"
)

// Injectors from wire.go:

// InitializeCLI собирает граф зависимостей и возвращает корневую команду CAP.
func InitializeCLI() (*command.RootCommand, error) {
	versionCommand := command.NewVersionCommand()
	pingCommand := command.NewPingCommand()
	repositoryRepository, err := repository.NewFileRepositoryRepository()
	if err != nil {
		return nil, err
	}
	repositoryService := service.NewRepositoryService(repositoryRepository)
	repositoryHandler := handler.NewRepositoryHandler(repositoryService)
	repositoryCommand := command.NewRepositoryCommand(repositoryHandler)
	cacheRepository, err := repository.NewFileCacheRepository()
	if err != nil {
		return nil, err
	}
	gitClient := external.NewExternalGitClient()
	updateService := service.NewUpdateService(repositoryRepository, cacheRepository, gitClient)
	updateHandler := handler.NewUpdateHandler(updateService)
	updateCommand := command.NewUpdateCommand(updateHandler)
	projectRepository := repository.NewFileProjectRepository()
	installedRepository := repository.NewFileInstalledRepository(projectRepository)
	marketplaceService := service.NewMarketplaceService(cacheRepository)
	installService := service.NewInstallService(cacheRepository, projectRepository, marketplaceService)
	installedService := service.NewInstalledService(installedRepository, marketplaceService, installService)
	installedHandler := handler.NewInstalledHandler(installedService)
	upgradeCommand := command.NewUpgradeCommand(installedHandler)
	selfUpdateRepository := external.NewGithubSelfUpdateClient()
	currentVersion := _wireCurrentVersionValue
	selfUpdateService := service.NewSelfUpdateService(selfUpdateRepository, currentVersion)
	selfUpdateHandler := handler.NewSelfUpdateHandler(selfUpdateService)
	selfUpdateCommand := command.NewSelfUpdateCommand(selfUpdateHandler)
	marketplaceHandler := handler.NewMarketplaceHandler(marketplaceService, installService)
	primitivesCommand := command.NewPrimitivesCommand(marketplaceHandler, installedHandler)
	rootCommand := command.NewRootCommand(versionCommand, pingCommand, repositoryCommand, updateCommand, upgradeCommand, selfUpdateCommand, primitivesCommand)
	return rootCommand, nil
}

var (
	_wireCurrentVersionValue = service.CurrentVersion(command.Version)
)
